export const ROUTE_NAME_INVENTORY = 'inventory'
export const ROUTE_NAME_RESERVATIONS = 'reservations'
export const ROUTE_NAME_CREATE_RESERVATION = 'create-reservation'
export const ROUTE_ICON_INVENTORY = 'fa-solid fa-cubes-stacked'
export const ROUTE_ICON_RESERVATIONS = 'fa-solid fa-calendar-check'
